"""Azure DevOps REST API client for pushing security requirements as work items."""

import logging
from base64 import b64encode

import httpx

logger = logging.getLogger(__name__)


class ADOClient:
    def __init__(self, org_url: str, project: str, pat: str):
        self.org_url = org_url.rstrip("/")
        self.project = project
        auth = b64encode(f":{pat}".encode()).decode()
        self.headers = {
            "Authorization": f"Basic {auth}",
            "Content-Type": "application/json-patch+json",
        }

    async def create_work_item(self, work_item_type: str, title: str, description: str, tags: str = "") -> dict:
        url = f"{self.org_url}/{self.project}/_apis/wit/workitems/${work_item_type}?api-version=7.1"
        payload = [
            {"op": "add", "path": "/fields/System.Title", "value": title},
            {"op": "add", "path": "/fields/System.Description", "value": description},
        ]
        if tags:
            payload.append({"op": "add", "path": "/fields/System.Tags", "value": tags})

        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(url, json=payload, headers=self.headers)
            resp.raise_for_status()
            data = resp.json()
            logger.info("Created ADO work item: %s", data.get("id"))
            return data

    async def add_comment(self, work_item_id: int, text: str) -> dict:
        """Add a comment to an existing work item."""
        url = f"{self.org_url}/{self.project}/_apis/wit/workitems/{work_item_id}/comments?api-version=7.1-preview.4"
        payload = {"text": text}
        headers = {**self.headers, "Content-Type": "application/json"}
        async with httpx.AsyncClient(timeout=30) as client:
            resp = await client.post(url, json=payload, headers=headers)
            resp.raise_for_status()
            data = resp.json()
            logger.info("Added comment to ADO work item: %s", work_item_id)
            return data

    async def publish_analysis_to_work_item(self, work_item_id: int, analysis: dict) -> dict:
        """Publish analysis results as a formatted HTML comment on an existing work item."""
        risk_score = analysis.get("risk_score", 0)
        abuse_cases = analysis.get("abuse_cases", [])
        requirements = analysis.get("security_requirements", [])
        stride_threats = analysis.get("stride_threats", [])

        # Build formatted HTML comment
        html = [
            "<h2>🛡️ SecureReq AI - Security Analysis</h2>",
            f"<p><strong>Risk Score:</strong> {risk_score}/100</p>",
            "<hr/>",
        ]

        if abuse_cases:
            html.append("<h3>⚠️ Abuse Cases Identified</h3>")
            html.append("<ul>")
            for ac in abuse_cases:
                html.append(f"<li><strong>{ac.get('threat', 'Unknown')}</strong><br/>")
                html.append(f"Actor: {ac.get('actor', 'N/A')} | Impact: {ac.get('impact', 'N/A')} | ")
                html.append(f"Likelihood: {ac.get('likelihood', 'N/A')} | STRIDE: {ac.get('stride_category', 'N/A')}</li>")
            html.append("</ul>")

        if requirements:
            html.append("<h3>🛡️ Security Requirements</h3>")
            html.append("<ul>")
            for req in requirements:
                html.append(f"<li><strong>[{req.get('priority', 'Medium')}] {req.get('id', '')}</strong>: {req.get('text', '')}</li>")
            html.append("</ul>")

        if stride_threats:
            html.append("<h3>📊 STRIDE Threat Analysis</h3>")
            html.append("<ul>")
            for st in stride_threats:
                html.append(f"<li><strong>[{st.get('category', '')}]</strong> {st.get('threat', '')} - Risk: {st.get('risk_level', 'N/A')}</li>")
            html.append("</ul>")

        html.append("<hr/><p><em>Generated by SecureReq AI</em></p>")

        comment_body = "".join(html)
        return await self.add_comment(work_item_id, comment_body)

    async def push_analysis(self, work_item_type: str, abuse_cases: list[dict], requirements: list[dict]) -> list[dict]:
        created = []
        for ac in abuse_cases:
            desc = f"<b>Threat Actor:</b> {ac.get('actor', '')}<br><b>Attack Vector:</b> {ac.get('attack_vector', '')}<br><b>Impact:</b> {ac.get('impact', '')}<br><b>Likelihood:</b> {ac.get('likelihood', '')}<br><b>STRIDE:</b> {ac.get('stride_category', '')}<br><br>{ac.get('description', '')}"
            result = await self.create_work_item(work_item_type, f"[Abuse Case] {ac.get('threat', '')}", desc, "security;abuse-case")
            created.append(result)

        for req in requirements:
            desc = f"<b>Priority:</b> {req.get('priority', '')}<br><b>Category:</b> {req.get('category', '')}<br><br>{req.get('text', '')}<br><br><b>Details:</b> {req.get('details', '')}"
            result = await self.create_work_item(work_item_type, f"[Security Req] {req.get('id', '')} - {req.get('text', '')[:80]}", desc, "security;requirement")
            created.append(result)

        return created
